"""
Drama Engine
------------
Calculates the entertainment value of a cricket match.
Uses the over-by-over timeline generated by TimelineBuilder.
"""

import pandas as pd


class DramaEngine:

    def __init__(self, timeline_df: pd.DataFrame):

        self.timeline = timeline_df.copy()

    # =====================================================
    # Calculate Drama
    # =====================================================

    def calculate(self):

        drama = 0

        explosive_overs = 0
        wicket_overs = 0
        pressure_overs = 0
        momentum_swings = 0
        big_shifts = 0

        previous_leader = None

        for _, row in self.timeline.iterrows():

            # ---------------------------------------------
            # Explosive Over
            # ---------------------------------------------

            if row["runs"] >= 18:

                explosive_overs += 1
                drama += 8

            elif row["runs"] >= 12:

                drama += 4

            # ---------------------------------------------
            # Wickets
            # ---------------------------------------------

            if row["wickets"] >= 2:

                wicket_overs += 1
                drama += 8

            elif row["wickets"] == 1:

                drama += 3

            # ---------------------------------------------
            # Pressure Over
            # ---------------------------------------------

            if row["runs"] <= 3:

                pressure_overs += 1
                drama += 2

            # ---------------------------------------------
            # Momentum Swings
            # ---------------------------------------------

            leader = row.get("leader", "Balanced")

            if previous_leader is not None:

                if (
                    leader != previous_leader
                    and leader != "Balanced"
                ):

                    momentum_swings += 1
                    drama += 10

            previous_leader = leader

            # ---------------------------------------------
            # Big Momentum Shift
            # ---------------------------------------------

            if row.get("big_shift", False):

                big_shifts += 1
                drama += 6

        # ---------------------------------------------
        # Final Over Bonus
        # ---------------------------------------------

        final_over = self.timeline[
            self.timeline["over"] == self.timeline["over"].max()
        ]

        if not final_over.empty:

            final_runs = int(final_over["runs"].sum())

            if final_runs >= 15:

                drama += 10

        # ---------------------------------------------
        # Cap Score
        # ---------------------------------------------

        drama = max(0, min(drama, 100))

        # ---------------------------------------------
        # Drama Level
        # ---------------------------------------------

        if drama >= 90:

            level = "Absolute Cinema"

        elif drama >= 75:

            level = "Thriller"

        elif drama >= 60:

            level = "High Drama"

        elif drama >= 40:

            level = "Competitive"

        else:

            level = "One-Sided"

        return {

            "drama_score": drama,

            "drama_level": level,

            "explosive_overs": explosive_overs,

            "wicket_overs": wicket_overs,

            "pressure_overs": pressure_overs,

            "momentum_swings": momentum_swings,

            "big_shifts": big_shifts

        }